import Produto from "../produto/Produto"



const produtos: Produto[] = [
    {
        id: 1,
        nome: 'Pedra de Massagem Facial de Jade',
        descricao: 'Pedra de jade para massagem facial, proporcionando relaxamento e benefícios para a pele.',
        marca: 'BeautyCare',
        modelo: 'Jade Premium',
        imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-cup-of-couple-6963130.jpg?alt=media&token=f9b9276d-2721-4b18-b87d-73131f6b390a',
        nota: 4.9,
        tags: ['Relaxamento', 'Skincare'],
        precoBase: 79.99,
        precoPromocional: 59.99,
        menorPreco: 49.99,
        maiorPreco: 89.99,
        precoMedio: 69.99,
        especificacoes: {
            destaque: 'Benefícios para circulação e relaxamento',
            Material: 'Jade natural',
            Uso: 'Massagem facial',
            Dimensões: '15cm x 5cm',
            Peso: '150g',
        },
    },
    {
        id: 2,
        nome: 'Sabonete Líquido Hidratante com Extrato de Aloe Vera',
        descricao: 'Sabonete líquido hidratante com extrato de aloe vera para uma limpeza suave e refrescante.',
        marca: 'Nature Bliss',
        modelo: 'Sabonete Líquido-300ml',
        imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-cup-of-couple-8015781.jpg?alt=media&token=8d54923d-ce58-4634-b8ff-46d9db4b3e25',
        nota: 4.7,
        tags: ['Hidratante', 'Aloe Vera'],
        precoBase: 49.99,
        precoPromocional: 39.99,
        menorPreco: 34.99,
        maiorPreco: 54.99,
        precoMedio: 44.99,
        especificacoes: {
            destaque: 'Limpeza suave e refrescante',
            Volume: '300ml',
            Gênero: 'Unissex',
            Tipo: 'Sabonete Líquido',
            Ingredientes: 'Extrato de Aloe Vera, Vitamina E',
        },
    },
    {
        id: 3,
        nome: 'Refil de Shampoo Revitalizante',
        descricao: 'Refil de shampoo revitalizante com extrato de plantas para cabelos mais fortes e saudáveis.',
        marca: 'GreenCare',
        modelo: 'Refil-500ml',
        imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-cup-of-couple-8015800.jpg?alt=media&token=571b7aa1-642b-49f1-a563-8aef0519e954',
        nota: 4.8,
        tags: ['Cabelos', 'Revitalização'],
        precoBase: 39.99,
        precoPromocional: 29.99,
        menorPreco: 24.99,
        maiorPreco: 49.99,
        precoMedio: 34.99,
        especificacoes: {
            destaque: 'Fortalece e hidrata os cabelos',
            Volume: '500ml',
            Tipo: 'Shampoo',
            Ingredientes: 'Extrato de plantas, Vitamina E',
        },
    },
    {
        id: 4,
        nome: 'Refil de Condicionador Nutritivo',
        descricao: 'Refil de condicionador nutritivo para cabelos hidratados e macios.',
        marca: 'GreenCare',
        modelo: 'Refil-500ml',
        imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-cup-of-couple-8015811.jpg?alt=media&token=e67849bf-ff69-4096-9e5a-5c9343be5036',
        nota: 4.7,
        tags: ['Hidratação', 'Nutrição'],
        precoBase: 49.99,
        precoPromocional: 39.99,
        menorPreco: 34.99,
        maiorPreco: 59.99,
        precoMedio: 44.99,
        especificacoes: {
            destaque: 'Hidratação intensa e brilho',
            Volume: '500ml',
            Tipo: 'Condicionador',
            Ingredientes: 'Óleo de Argan, Vitamina B5',
        },
    },
    {
        id: 5,
        nome: 'Creme Hidratante Corporal Rosas',
        descricao: 'Hidratante corporal com fragrância de rosas, ideal para peles ressecadas.',
        marca: 'Natura',
        modelo: 'Rosas-400ml',
        imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-cup-of-couple-8015894.jpg?alt=media&token=537f0fc0-8504-4512-9a63-82aa3ec67aa5',
        nota: 4.6,
        tags: ['Hidratação', 'Pele Seca'],
        precoBase: 39.99,
        precoPromocional: 29.99,
        menorPreco: 24.99,
        maiorPreco: 49.99,
        precoMedio: 34.99,
        especificacoes: {
            destaque: 'Hidratação Intensa',
            Volume: '400ml',
            Uso: 'Corpo',
            Tipo: 'Hidratante',
        },
    },
    {
        id: 6,
        nome: 'Incenso Natural de Sândalo',
        descricao: 'Incenso natural com fragrância suave de sândalo, ideal para aromatizar ambientes.',
        marca: 'Zen Aroma',
        modelo: 'Sândalo-12 unidades',
        imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-ekaterina-bolovtsova-6766581.jpg?alt=media&token=796d22fd-8b7b-458b-8d40-74a4c4265d53',
        nota: 4.8,
        tags: ['Relaxamento', 'Aromaterapia'],
        precoBase: 19.99,
        precoPromocional: 15.99,
        menorPreco: 14.99,
        maiorPreco: 24.99,
        precoMedio: 17.99,
        especificacoes: {
            destaque: 'Fragrância relaxante',
            Quantidade: '12 unidades',
            Tipo: 'Incenso natural',
        },
    },
    {
        id: 7,
        nome: 'Vela Aromática Baunilha',
        descricao: 'Vela aromática com suave fragrância de baunilha, ideal para momentos relaxantes.',
        marca: 'CandleLux',
        modelo: 'Baunilha-300g',
        imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-rdne-8903616.jpg?alt=media&token=cfa43d3e-fb89-4247-94a9-9bce23eae380',
        nota: 4.9,
        tags: ['Relaxamento', 'Aromaterapia'],
        precoBase: 59.99,
        precoPromocional: 49.99,
        menorPreco: 39.99,
        maiorPreco: 69.99,
        precoMedio: 54.99,
        especificacoes: {
            destaque: 'Fragrância suave de baunilha',
            Peso: '300g',
            Duração: '45 horas',
            Material: 'Cera vegetal',
        },
    },
    {
      id: 8,
      nome: 'Óleo de Banho Calmante de Lavanda',
      descricao: 'Óleo de banho com fragrância calmante de lavanda, ideal para relaxamento e hidratação da pele.',
      marca: 'CandleLux',
      modelo: 'Lavanda Soft',
      imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-tara-winstead-6693965.jpg?alt=media&token=9dbca490-5122-4ea6-b1b8-728fd47c79ba',
      nota: 4.9,
      tags: ['Relaxamento', 'Lavanda'],
      precoBase: 59.99,
      precoPromocional: 49.99,
      menorPreco: 44.99,
      maiorPreco: 69.99,
      precoMedio: 54.99,
      especificacoes: {
          destaque: 'Fragrância calmante de lavanda',
          Volume: '200ml',
          Ingredientes: 'Óleo de lavanda, Vitamina E',
          Uso: 'Banho',
          Tipo: 'Óleo Corporal',
      },
  },
  {
      id: 9,
      nome: 'Difusor de Aromas de Bamboo',
      descricao: 'Difusor de aromas com fragrância natural de bamboo, perfeito para ambientes frescos e energizantes.',
      marca: 'EcoAroma',
      modelo: 'Bamboo Fresh-100ml',
      imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-tara-winstead-6694131.jpg?alt=media&token=df17efe1-8b98-435e-9a97-42b1531a1f10',
      nota: 4.8,
      tags: ['Aromaterapia', 'Decoração'],
      precoBase: 49.99,
      precoPromocional: 39.99,
      menorPreco: 34.99,
      maiorPreco: 59.99,
      precoMedio: 44.99,
      especificacoes: {
          destaque: 'Fragrância fresca de bamboo',
          Volume: '100ml',
          Tipo: 'Difusor de Aromas',
          Material: 'Bamboo natural',
      },
  },
  {
    id: 10,
    nome: 'Óleo Essencial de Lavanda',
    descricao: 'Óleo essencial puro de lavanda, conhecido por suas propriedades calmantes e relaxantes, perfeito para aromaterapia.',
    marca: 'NatureAroma',
    modelo: 'Lavanda Pura 10ml',
    imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-tara-winstead-6694135.jpg?alt=media&token=78d41073-cee2-4fa9-a8ea-f04ff7788559',
    nota: 4.8,
    tags: ['Aromaterapia', 'Relaxamento', 'Lavanda'],
    precoBase: 29.99,
    precoPromocional: 24.99,
    menorPreco: 19.99,
    maiorPreco: 34.99,
    precoMedio: 27.99,
    especificacoes: {
        destaque: 'Óleo essencial 100% puro',
        Volume: '10ml',
        Ingredientes: 'Óleo essencial de Lavandula angustifolia',
        Uso: 'Aromaterapia, Difusores, Banhos',
        Tipo: 'Óleo Essencial',
    },
}
] 

export default produtos