import { Produto } from '../produto'

const produtos: Produto[] = [
    {
      id: 1,
      nome: 'Iluminador Facial Glow Intenso',
      descricao: 'Iluminador facial para destacar os pontos altos do rosto com brilho intenso e acabamento natural.',
      marca: 'GlowUp',
      modelo: 'Glow Intenso 24K',
      imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-content-prod-co-5908368.jpg?alt=media&token=1d0b1ec2-d68d-4d1d-8a76-1b6c1d28631f',
      nota: 4.9,
      tags: ['Mais Vendido'],
      precoBase: 69.99,
      precoPromocional: 49.99,
      menorPreco: 39.99,
      maiorPreco: 79.99,
      precoMedio: 59.99,
      especificacoes: {
          destaque: 'Acabamento cintilante e natural',
          'Duração': '8 horas',
          'Peso': '10g',
          'Composição': 'Micas naturais, pigmentos minerais',
          'Altura': '5 cm',
          'Largura': '5 cm',
        },
    },
    {
        id: 2,
        nome: 'Spray Floral Rosé',
        descricao:
            'Spray com notas florais e toque de baunilha, ideal para o dia a dia.',
        marca: 'Floral Sense',
        modelo: 'Rosé Delight',
        imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-artempodrez-6800943.jpg?alt=media&token=256aae47-caee-479e-b04a-34dd6f2aebcd',
        nota: 4.7,
        tags: [],
        precoBase: 149.99,
        precoPromocional: 129.99,
        menorPreco: 99.99,
        maiorPreco: 189.99,
        precoMedio: 139.99,
        especificacoes: {
            destaque: 'Notas de rosa e baunilha',
            Capacidade: '100 ml',
            Tipo: 'Eau de Parfum',
            'Duração': 'Até 8 horas',
            'Peso': '350g',
        },
    },
    {
        id: 3,
        nome: 'Difusor de Ambiente Citrus Fresh',
        descricao:
            'Difusor de ambiente com fragrância cítrica para energizar o espaço.',
        marca: 'Aroma Home',
        modelo: 'Citrus Fresh 250ml',
        imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-eva-bronzini-6914777.jpg?alt=media&token=b1fbb429-2c73-4b33-9c5f-5d46c6b84437',
        nota: 4.6,
        tags: [],
        precoBase: 79.99,
        precoPromocional: 69.99,
        menorPreco: 59.99,
        maiorPreco: 89.99,
        precoMedio: 74.99,
        especificacoes: {
            destaque: 'Fragrância cítrica refrescante',
            Capacidade: '250 ml',
            'Duração': 'Até 60 dias',
            Peso: '400g',
            Material: 'Vidro reciclável',
        },
    },
    {
        id: 4,
        nome: 'Oléo de Banho',
        descricao:
            'Oléo de Banho com toque suave de baunilha, ideal para criar ambientes acolhedores.',
        marca: 'CandleLux',
        modelo: 'Baunilha Soft',
        imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-alesiakozik-7796592.jpg?alt=media&token=7a26bd87-9ba9-448e-bd70-42f0da36a3cb',
        nota: 4.9,
        tags: ['Recomendado'],
        precoBase: 59.99,
        precoPromocional: 49.99,
        menorPreco: 39.99,
        maiorPreco: 69.99,
        precoMedio: 54.99,
        especificacoes: {
            destaque: 'Aroma suave de baunilha',
            Duração: '12 horas',
            Peso: '250g',
            Composição: 'Oléo de soja',
            'Altura': '9 cm',
            'Largura': '7 cm',
        },
    },
    {
      id: 5,
      nome: 'Vela Aromática Lavanda',
      descricao: 'Vela aromática com fragrância relaxante de lavanda, ideal para ambientes tranquilos.',
      marca: 'Essence',
      modelo: 'Lavanda-250g',
      imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-karolina-grabowska-8947557.jpg?alt=media&token=fc4a326a-6a84-4bcf-86af-dc6423c38771',
      nota: 4.7,
      tags: ['Oportunidade'],
      precoBase: 49.99,
      precoPromocional: 39.99,
      menorPreco: 35.99,
      maiorPreco: 59.99,
      precoMedio: 44.99,
      especificacoes: {
          destaque: 'Fragrância de Lavanda',
          Peso: '250g',
          Duração: '40 horas',
          Material: 'Cera vegetal',
      },
  },
  {
    id: 6,
    nome: 'Pedra de Massagem Facial de Jade',
    descricao: 'Pedra de jade para massagem facial, proporcionando relaxamento e benefícios para a pele.',
    marca: 'BeautyCare',
    modelo: 'Jade Premium',
    imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-cup-of-couple-8015471.jpg?alt=media&token=e5b22fcc-5e0d-437b-ba8e-027c210a25e8',
    nota: 4.9,
    tags: ['Relaxamento', 'Skincare'],
    precoBase: 79.99,
    precoPromocional: 59.99,
    menorPreco: 49.99,
    maiorPreco: 89.99,
    precoMedio: 69.99,
    especificacoes: {
        destaque: 'Benefícios para circulação e relaxamento',
        Material: 'Jade natural',
        Uso: 'Massagem facial',
        Dimensões: '15cm x 5cm',
        Peso: '150g',
      },
  },
  {
    id: 7,
    nome: 'Creme Hidratante Facial com Ácido Hialurônico',
    descricao: 'Creme facial hidratante com ácido hialurônico para uma pele mais suave e radiante.',
    marca: 'HydraSkin',
    modelo: 'Hidratante Premium-50ml',
    imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-cup-of-couple-6963142.jpg?alt=media&token=a3edc000-d270-4c4d-b898-628d68a8f14e',
    nota: 4.8,
   
    tags: ['Hidratação', 'Skincare'],
    precoBase: 199.99,
    precoPromocional: 159.99,
    menorPreco: 149.99,
    maiorPreco: 219.99,
    precoMedio: 179.99,
    especificacoes: {
        destaque: 'Hidratação intensa e rápida absorção',
        Volume: '50ml',
        Gênero: 'Unissex',
        Tipo: 'Creme Hidratante',
        Ingredientes: 'Ácido Hialurônico, Vitamina E',
      },
  },
  {
      id: 8,
      nome: 'Difusor de Aromas Bamboo',
      descricao: 'Difusor com fragrância de bamboo, ideal para perfumar e decorar ambientes.',
      marca: 'Aroma Home',
      modelo: 'Bamboo-200ml',
      imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-sydnee-more-30355262-6958992.jpg?alt=media&token=fdd1a1bb-c195-4111-89ca-1567c94f3104',
      nota: 4.8,
      tags: ['Decoração', 'Aromaterapia'],
      precoBase: 79.99,
      precoPromocional: 69.99,
      menorPreco: 59.99,
      maiorPreco: 89.99,
      precoMedio: 74.99,
      especificacoes: {
          destaque: 'Fragrância Refrescante',
          Volume: '200ml',
          Duração: '3 meses',
          Tipo: 'Difusor de varetas',
      },
  },
  {
    id: 9,
    nome: 'Sabonete Líquido Hidratante com Extrato de Aloe Vera',
    descricao: 'Sabonete líquido hidratante com extrato de aloe vera para uma limpeza suave e refrescante.',
    marca: 'Nature Bliss',
    modelo: 'Sabonete Líquido-300ml',
    imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-karolina-grabowska-4210371.jpg?alt=media&token=bcf1cb82-d070-41fb-88c6-4874d3f40664',
    nota: 4.7,
    tags: ['Hidratante', 'Aloe Vera'],
    precoBase: 49.99,
    precoPromocional: 39.99,
    menorPreco: 34.99,
    maiorPreco: 54.99,
    precoMedio: 44.99,
    especificacoes: {
        destaque: 'Limpeza suave e refrescante',
        Volume: '300ml',
        Gênero: 'Unissex',
        Tipo: 'Sabonete Líquido',
        Ingredientes: 'Extrato de Aloe Vera, Vitamina E',
      },
  },
  {
      id: 10,
      nome: 'Creme Hidratante Corporal Rosas',
      descricao: 'Hidratante corporal com fragrância de rosas, ideal para peles ressecadas.',
      marca: 'Natura',
      modelo: 'Rosas-400ml',
      imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-karolina-grabowska-4735943.jpg?alt=media&token=02ac5bbf-79bc-4018-9b2a-87beb94d5ec5',
      nota: 4.6,
      tags: ['Hidratação', 'Pele Seca'],
      precoBase: 39.99,
      precoPromocional: 29.99,
      menorPreco: 24.99,
      maiorPreco: 49.99,
      precoMedio: 34.99,
      especificacoes: {
          destaque: 'Hidratação Intensa',
          Volume: '400ml',
          Uso: 'Corpo',
          Tipo: 'Hidratante',
      },
  },
  {
    id: 12,
    nome: 'Óleo Perfumado Jasmim',
    descricao: 'Óleo corporal perfumado com fragrância suave de jasmim.',
    marca: 'L’Occitane',
    modelo: 'Jasmim-100ml',
    imagem: 'https://firebasestorage.googleapis.com/v0/b/ecommerce-fb616.appspot.com/o/pexels-yankrukov-7019751.jpg?alt=media&token=c356831c-1e10-4145-9e63-cefefa2af938',
    nota: 4.7,
    tags: ['Hidratação', 'Perfume Corporal'],
    precoBase: 99.99,
    precoPromocional: 89.99,
    menorPreco: 84.99,
    maiorPreco: 109.99,
    precoMedio: 94.99,
    especificacoes: {
        destaque: 'Perfume Suave',
        Volume: '100ml',
        Uso: 'Corpo',
        Tipo: 'Óleo Hidratante',
      },
  },
]
export default produtos